### ISSUE TITLE
How to recieve NMT messages from multiple nodes

### ISSUE THREAD

**Issue by DylanRobertBennett** [CANopenNode/CANopenLinux#4]
Background: 
I’m working on a Linux based application, based on the CANOpenLinux example, that acts as a master and interfaces to a number of CANopen nodes as slaves. 

I’m able to use multi OD support and issue NMT and PDOs to each of the nodes, and using a locally implemented ‘master node’ receive RPDOs from other nodes. I used  

```
void canOpenProcess() { 
    CO_epoll_wait(&epMain); 
    CO_epoll_processRT(&epMain, nodeInstance[NodeID::Master].pCOInstance, false); 
    CO_epoll_processMain(&epMain, nodeInstance[NodeID::Master].pCOInstance, false, NULL); 
    CO_epoll_processLast(&epMain); 
} 
```

```
while(!shutdownApplication) {        	 
          std::this_thread::sleep_for(std::chrono::milliseconds(1000)); 
          canOpenProcess();
} 
```

Issue: 
I’d like to track the state of the other nodes on the bus so I can properly configure them and act when their states change. 

Is there a mechanism in CanOpenNode to receive callbacks when nodes on the bus announce their NMT state changes? 

CO_NMT_initCallbackPre() looks like an option but this and CO_NMT_initCallbackChanged() appear geared to a CANopen slave use case, not that of a master looking to track the state of several slave nodes.

**Comment by rashcroft7** [comment]
@bennettbe I am working on a similar project using CANOpenLinux acting as a master interfacing with several slaves.  Can you give me some insight on how succesful you were using CANOpenLinux for this and possibly point me in the right direction to configure it correctly.

I understand CO_MULTIPLE_OD is used for this, but documentation is limited.
